# Generated by Django 4.2.5 on 2023-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
