# Generated by Django 4.2.5 on 2023-09-17 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0004_remove_exercise_id_exercise_exercise_id'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='repetitions',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='rpe',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='set_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='set_type',
            field=models.CharField(choices=[('Warmup', 'Working')], default='Working', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(default='', through='workout.WorkoutExercise', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='note',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workout',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='exercises.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='sets',
            field=models.ManyToManyField(to='workout.exerciseset'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='workout.workout'),
            preserve_default=False,
        ),
    ]
