# Generated by Django 4.2.5 on 2023-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='bodypart',
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('CH', 'Chest'), ('LB', 'Lowerback'), ('UB', 'Upperback'), ('LE', 'Legs'), ('C', 'Core'), ('AR', 'Arms'), ('SH', 'Shoulder'), ('CO', 'Condition')], default='CH', max_length=2),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user_gear',
            field=models.CharField(choices=[('BB', 'Barbell'), ('BA', 'Bar'), ('DS', 'DISC'), ('BW', 'Bodyweight'), ('CB', 'Cable'), ('NN', 'None')], default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
