# Generated by Django 4.2.5 on 2023-09-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_exercise_bodypart_exercise_body_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.TextField(default='', max_length=60),
        ),
    ]
