# Generated by Django 4.2.5 on 2023-09-17 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
